default: &default
  appid: "wx3d710c33ad82e8f2"
  secret: "40f505430f60ca0e5c0159c8ac79db4f"
  token: "b333b63d985de6"
  access_token: "/var/tmp/wechat_access_token"
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"
  encrypt_mode: false
  encoding_aes_key:  "QidXCRLVNuvC2LxZVuwK6HerHWiczDospF43BRY70zK"

production:
  <<: *default
development:
  <<: *default
  trusted_domain_fullname: "http://niucang.s1.natapp.cc"

test:
  <<: *default
