default: &default
  appid: "wxf21a7f12034721c9"
  secret: "ae9a22bf2a293ffece5f9346c0b2e033"
  token: "b333b63d985de6"
  access_token: "/var/tmp/wechat_access_token"
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"
  encrypt_mode: false
  encoding_aes_key:  "QidXCRLVNuvC2LxZVuwK6HerHWiczDospF43BRY70zK"

production:
  <<: *default
development:
  <<: *default
  trusted_domain_fullname: "http://niucang.s1.natapp.cc"

test:
  <<: *default
